### ISSUE TITLE
UTF-8 path

### ISSUE THREAD

**Issue by Nick222** [rkokkelk/todo.txt-ext#1]
Can I use UTF-8 codepage path to todo.txt?
Xubuntu 15.04
Thunderbird 38.2.0
(and what additional application I must to install to start work - except Lightning?)

**Comment by rkokkelk** [comment]
Hi,

the add-on is developed as an extension of the Todo.txt application. In order to get it to work you only need Thunderbird with the Lightning add-on. Regarding setting your path, you'll just can use the Thunderbird properties menu so you don't have to manually type in the exact path.
