### ISSUE TITLE
error after recent update 

### ISSUE THREAD

**Issue by muralikodali** [rkokkelk/todo.txt-ext#12]
Following is the message shown:

An error was encountered preparing the calendar located at todotxt://_unused for use. It will not be available.

[Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///usr/lib/thunderbird/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js :: cmgr_createCalendar :: line 440"  data: no]

**Comment by rkokkelk** [comment]
Hey, thank you for the feedback. Unfortunately I'm currently on holiday so I can't fix this issues this instant. As soon as I return I'll look into it and fix it ASAP. 

Good you please specify when you encounter the issue. For example, when installing the add-on or when adding a task. Again thank you for your feedback.

**Comment by firmgently** [comment]
Hi I'm not sure if this extra info helps but:

I'm a new user, after installing 0.7 I get the same errors as above. It happens every time I start Thunderbird 38.7.0 (it's actually Icedove as I'm on Debian but as far as I know it's exactly the same code just with a different name and icon).

I downgraded to 0.6.2 and it seems ok. Nice add-on btw :)

**Comment by muralikodali** [comment]
Sir,

Whenever i start thunderbird, i am getting the error.
Pls find attached screen shot for more info.

-- 
Regards,
Murali Kodali

**Comment by rkokkelk** [comment]
Thank you both, 

I have enough information to fix this as soon as I get back from my holiday. Expect a fix to be published around the 8th of August. My apologies for the issues, further progress will be shown on this page.

**Comment by rkokkelk** [comment]
Issues is related to the `setInterval()` function used in the new synchronization process. This function is only available in the recent Thunderbird versions (45.*) and not the older stable versions (38.*). 

I'll currently searching for similar functionality which will be available within both versions.

**Comment by rkokkelk** [comment]
Issue is fixed, the next release 0.7.1 is now verified by Mozilla and will be available in the next couple of days. When released users with Thunderbird (Icedove) with older versions will be available to use the add-on.

**Comment by muralikodali** [comment]
Now todo.txt addon is functional again.But there is some difference with previous one.
previously tasks are **shown in the calendar along task list**. Now they are showing up in task list only.

**Comment by rkokkelk** [comment]
This is a configuration option, you can restore this by enabling the *Use the Todo's creation timestamp* option within the Add-on. This functionality should ensure that the tasks are also visible within the calendar.
