### ISSUE TITLE
Installing the extension makes Thunderbird inoperable

### ISSUE THREAD

**Issue by sorinsfirlogea** [rkokkelk/todo.txt-ext#19]
After installing the extension Thunderbird becomes really sluggish. A number of scripts are reporting that are having execution problems and there are several dialog boxes inviting me to stop them. Even if I do it, another script is hanging and Thunderbird is still sluggish. One of the scripts (as an example) is calendar-ui-utils.js at line 522.

Environment: Ubuntu 14.04, KDE destop, Thunderbird 45.6.0.

**Comment by rkokkelk** [comment]
Hi,

Thank you for mentioning the bug, I'll start working on it immediately. Are you using Ubuntu with KDE desktop or directly Kubuntu? Also are you using any additional add-on so that I can check compatibility with them.

Thank you again.

**Comment by sorinsfirlogea** [comment]
I'm running a Kubuntu box. Other extensions installed:
Account Colors
AddressBookTab
Awesome Auto Archive
Calendar Tweaks
Close Tab on Esc
Contact Tabs
DOM Inspector
Duplicate Contact Manager
Extra Format Buttons
FireTray
Flat Folder Tree
gContact Sync
Lightning
mailmindr
Manually sort folders
NewScrollbars
Provider for Google Calendar
Restart application
Rise of the Tools
Stationery
Stylish
SuperDate Format
Toolbar Buttons

Phiiiiuuuu! Quite a few, I admit.

Regards,
Sorin

**Comment by sorinsfirlogea** [comment]
Any news? Did you get the chance to investigate the issue?
Thanks.

**Comment by sorinsfirlogea** [comment]
So, I disabled all add-ons except Lightning and Todo.txt and then I enabled them back, one by one. Don't know why, but now it works. Is not sluggish anymore. Still, when I interact with the todo.txt file (adding or modifying a task) I keep getting a warning that says: oDoneStream is not defined. Then there is a Thunderbird calendar error: An error occurred when writing to the calendar Todo.txt!
Also I cannot delete a task, I get a warning saying: util.getToDo is not a function.

**Comment by JoergPalmer** [comment]
I saw this happening for me as well. For me it happened as long as the configuration -in particular the file locations- were not set. I could either kill TB and add the settings manually in the prefs.js or be real patient as the configuration dialog pops up after a real long while. As soon as the file locations were entered properly for me the problem had gone.

Maybe that helps in spotting the problem?

**Comment by sorinsfirlogea** [comment]
Nope, I don't think that this is the problem in my case. I checked pref.js and the configuration is correct. Also I am not experiencing a delay of the configuration dialog, because... there is no configuration dialog. In my case configurations are placed at the end of the addon information text, so if I press the Preferences button or the More button I have the same behaviour (see the snapshot)
![image](https://cloud.githubusercontent.com/assets/9035273/22237893/32d77620-e217-11e6-9689-ee3ec8c9c448.png)

**Comment by rkokkelk** [comment]
My sincere apologies, I've made a small error within the code which resulted in the issue. A new version is uploaded to Mozilla and should be made available within the next few days which will resolve this issue. I will close this issue but if the fix was not sufficient or if there are other relevant issues please let me know and please feel free to reopen this issue.

Thank you for reporting this.
