### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by rkokkelk** [rkokkelk/todo.txt-ext#2]
User notified that there are issues with UTF-8 encoding of certain characters.

(A) Zavolať Blabláčová
(B) Napísať pre Štefana Tótha +Nákup
2015-11-17 Napísať voľačo 94 +Nákup
Police @Vymyslieť +Kuchyňa
This is test task with local characters ľščťžýáíéúô
This is test task with due due:2015-11-19
This is test task with time t:2015-11-17

**Comment by johannesgunnar** [comment]
Can confirm, noticed a similar thing with icelandic characters (þæöíóéýúáð). Although oddly enough characters display OK if todo item is added with todo.txt-ext in Thunderbird, but if added with any other external tool they get displayed incorrectly.

![screenshot](https://cloud.githubusercontent.com/assets/2924543/11639029/1a816a76-9d22-11e5-901b-f636d81ed61e.png)

**Comment by rkokkelk** [comment]
Thank you for the feedback. I'll try to fix this problem during the next release. Which external tool did you use which resulted in the characters displayed incorrectly. This might help to reproduce the problem.

**Comment by rkokkelk** [comment]
I've implemented a fix and this will be distributed during the next release. Which will be send to Mozilla this week.

**Comment by johannesgunnar** [comment]
Seems like the extension has been updated now and everything is working fine. Good job! thank you very much!

To expand on how to reproduce the problem, the above screenshot was tested with todo.sh in vanilla Ubuntu terminal. All other todo entries (with icelandic letters) were corrupted and they were most likely added either through the terminal (todo.sh), qtodotxt or a text editor (gedit and/or atom)
