### ISSUE TITLE
the plugin does not write to the file

### ISSUE THREAD

**Issue by MrDave75** [rkokkelk/todo.txt-ext#24]
Hi, I installed the plugin on thunderbird latest version (45.7.1), but I can not make it work. When I insert a new Task, the plugin does not update the file leaving it empty. If i manually add a line to the file, thunderbird shows correctly, but if I try to edit it keeps me the original version, without reporting any error. What can I check? Using Windows 10 64bit
Thank's

**Comment by rkokkelk** [comment]
Hi,

This is defintely a bug and thank you for reporting it. Could you specify whether you are using the latest version of the add-on `0.8.2`. Also if you are able could you give me an example of your Todo.txt and Done.txt file so that I can use it to verify the bug.

Thank you again!

**Comment by MrDave75** [comment]
Hi, I use the version 0.8.2; I also tried it with version 0.8.1, but nothing changes. Both files are empty because I started from a clean install, but I have also tried using the sample files found on the site todo.txt. I also tried to install the plugin on a clean installation of thunderbird but I always have the problem

**Comment by zisrem** [comment]
I just found this great extension for Thunderbird and first had the same problem. I am unsing Windows 10, Thunderbird 45.7.1 in German and version 0.8.2 of this plugin and at first I was not able to write to the todo.txt file. To fix the problem you need to run Thunderbird as administrator to get the full access to to the todo.txt file. Now I am realy happy, thank you for this great little plugin!

**Comment by rkokkelk** [comment]
Hi,

Thank you for your update. I've tried to reproduce the error but I got some similar error that sometimes it works and another time it does not. This makes fixing this issue a little bit more challeging. But I will try to fix this issue as soon as possible.

**Comment by rkokkelk** [comment]
Fix for this issue has been added and new version `0.8.3` has been submitted to Mozilla. If this issue persists in the next version please feel free to reopen this issue so that I can investigate it further.

**Comment by MrDave75** [comment]
Hi, I upgraded pluging and now write the file works correctly. But I
    notice that if I add a category in one activity, this is not saved,
    but during synchronization is eliminated. It's normal?
    
      
      
      
      Thank You
      
      
        
        
      
    
    Il 26/02/2017 20:31, Roy Kokkelkoren ha
      scritto:
    
    
      Fix for this issue has been added and new version 0.8.3
        has been submitted to Mozilla. If this issue persists in the
        next version please feel free to reopen this issue so that I can
        investigate it further.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rkokkelk/todo.txt-ext","title":"rkokkelk/todo.txt-ext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rkokkelk/todo.txt-ext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rkokkelk in #24: Fix for this issue has been added and new version `0.8.3` has been submitted to Mozilla. If this issue persists in the next version please feel free to reopen this issue so that I can investigate it further."}],"action":{"name":"View Issue","url":"https://github.com/rkokkelk/todo.txt-ext/issues/24#issuecomment-282580458"}}}

**Comment by rkokkelk** [comment]
Hi,

You are right that should not happen. I have opened a new issue for this bug #25, and will resolve it a.s.a.p.

Thank you for mentioning it.
