### ISSUE TITLE
New categories are not saved

### ISSUE THREAD

**Issue by rkokkelk** [rkokkelk/todo.txt-ext#25]
Hi, I upgraded pluging and now write the file works correctly. But I notice that if I add a category in one activity, this is not saved, but during synchronization is eliminated. It's normal?

Mentioned at #24.

**Comment by rkokkelk** [comment]
@MrDave75, could you specify which options you have selected. If you have enabled the 'Show Projects and Contexts in the title' option and if you then alter the Thunderbird categories, the changes will not be written.

This is because you have specified that the categories and projects will be shown in the title. If you disable this option, changing the Thunderbird categories should work accordingly. Could you verify this?

**Comment by MrDave75** [comment]
Sorry, you're right. I removed the check and now works correctly
    
      
      
      
      Thank You
      
    
    Il 27/02/2017 15:39, Roy Kokkelkoren ha
      scritto:
    
    
      @MrDave75, could you specify which
        options you have selected. If you have enabled the 'Show
        Projects and Contexts in the title' option and if you then alter
        the Thunderbird categories, the changes will not be written.
      This is because you have specified that the categories and
        projects will be shown in the title. If you disable this option,
        changing the Thunderbird categories should work accordingly.
        Could you verify this?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rkokkelk/todo.txt-ext","title":"rkokkelk/todo.txt-ext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rkokkelk/todo.txt-ext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rkokkelk in #25: @MrDave75, could you specify which options you have selected. If you have enabled the 'Show Projects and Contexts in the title' option and if you then alter the Thunderbird categories, the changes will not be written.\r\n\r\nThis is because you have specified that the categories and projects will be shown in the title. If you disable this option, changing the Thunderbird categories should work accordingly. Could you verify this?"}],"action":{"name":"View Issue","url":"https://github.com/rkokkelk/todo.txt-ext/issues/25#issuecomment-282738176"}}}

**Comment by rkokkelk** [comment]
Okay, great that it works now, I will therefore close this issue. 

Thank you again for reporting any issues with the add-on.
