### ISSUE TITLE
Lock file!

### ISSUE THREAD

**Issue by heX16** [rkokkelk/todo.txt-ext#30]
After press "Synchronize" file is locked.
Every click of the "sync" button increases the number of open handles (see in OpenedFilesView.exe).

(may be need "close" function in [this](https://github.com/rkokkelk/todo.txt-ext/blob/90163295e3fc20d4ee2a8974196998d84307c267/modules/fileUtil.jsm#L62) function?)

OS: Windows 7 x64.
Synchronization soft: Syncthing v0.14.31

![1111111111111111111111111111111](https://user-images.githubusercontent.com/3930496/27683248-f573e606-5ccd-11e7-90a2-d98a4a936b01.png)
![2222222222222222222](https://user-images.githubusercontent.com/3930496/27683249-f5a1703a-5ccd-11e7-9958-0e57fb5db936.png)

**Comment by rkokkelk** [comment]
Thank you for this issue, it is probably related to issue #29. I'll put some extra effort into rewriting the opening and closing of the todo.txt files. My apologies for the delay.

**Comment by rkokkelk** [comment]
I've resolved this issue, see the description at #29. If you still continue to have issues please let me know by reopening issue #29. Thank you!
