### ISSUE TITLE
input.split is not a function

### ISSUE THREAD

**Issue by bowdrillGit** [rkokkelk/todo.txt-ext#33]
I am getting a warning box with title: "Warning ToDo.txt" and contents "input.split is not a function".  Tasks in my todo.txt do not show up in tasks

Thunderbird 52.2.1 64-bit on Ubuntu 16.04.02
Lightning 5.4

**Comment by bowdrillGit** [comment]
Lighting 5.4

**Comment by rkokkelk** [comment]
Hi,

Could you elaborate on the issue. More specifically which version of the add-on are you using? And could you supply me with an example of you todo.txt and done.txt file so that I can use this to verify and possible fix this issue.

Thank you for your help!

**Comment by rkokkelk** [comment]
Closed due to no response. If you have any further questions please feel free to reopen this issue.
