### ISSUE TITLE
Category not working

### ISSUE THREAD

**Issue by unicolyon** [rkokkelk/todo.txt-ext#34]
Hi,

Each time I add a category, it correctly writes the +Category in the file.
However, each time the calendar synchronizes (I suppose that it then read the file), the +Category is not properly considered as a category but is written in extenso in the title of the task.

**Comment by rkokkelk** [comment]
Hi, 

The add-on has an option whether the Categories etc are prosecced either in the title or as seperate categories. Have you tried changing this option in the settings?

**Comment by rkokkelk** [comment]
Closed due to no response. If you have any further questions please feel free to reopen this issue.

**Comment by unicolyon** [comment]
The "see projects and contexts in the title" is unticked, so it should not be that.

Btw sorry for the delay but I did not received any notification concerning your answer (only for the issue closing)
