### ISSUE TITLE
issue solved

### ISSUE THREAD

**Issue by yosirn** [rkokkelk/todo.txt-ext#35]
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getComplexValue]
Thunderbird 45.8

**Comment by Hillside502** [comment]
Best to update to latest Thunderbird 52.3.0

Download in your language — Mozilla Thunderbird
https://www.mozilla.org/en-US/thunderbird/all/

**Comment by rkokkelk** [comment]
HHi,

@yosirn have you updated to the latest release of TB and did this resolve this issue. I'll look into the fact why the warning is shown in TB 45.8 but it helps if I know it is not an issue in more modern versions of TB.

**Comment by yosirn** [comment]
Hi @rkokkelk yes updating TB solved the issue thanks

**Comment by Hillside502** [comment]
@yosirn 
Best to keep the original issue title (or improve it) --- changing to "issue solved" becomes meaningless in the list of all issues.

**Comment by rkokkelk** [comment]
Thanks for the update, that will help to locate the bug. I'll keep this issue open until it is resolved in the earlier versions of TB .

**Comment by rkokkelk** [comment]
I've found the reason for this bug. This occurs if you first open the add-on and you have not specified the todo.txt or done.txt file locations. This code has now been reformatted and should show clear error messages if the todo.txt and done.txt file has not been specified. 

The new version with fixes has been uploaded to Thunderbird add-ons page and should be made available in the next few days. If there are still any issues, please feel free to reopen this issue.
