### ISSUE TITLE
Why Github version is 0.6.1 and 0.8.6 in Mozilla Add-on ?

### ISSUE THREAD

**Issue by KTylen** [rkokkelk/todo.txt-ext#36]
Hello, everything is in the title ;-) Also I've the same warning issue as the previous post.

Thanks

edit: My Thunderbird is 52.2.1

**Comment by Hillside502** [comment]
Releases · rkokkelk/todo.txt-ext
https://github.com/rkokkelk/todo.txt-ext/releases
has not been updated for **16 months**

Latest Tbird is 52.3.0

**Comment by rkokkelk** [comment]
Hi Guys,

Well to be honest, I'm not updating the tags/releases properly of the project because I thought that most users us the TB website to get the latest version of the application. However, if you guys prefer I can put a bit more focus on keeping the tags/releases up to date.

**Comment by Hillside502** [comment]
Suggest keeping both up-to-date.

**Comment by KTylen** [comment]
GOOD NEWS !
I know now where come the "Modification fail" that experience a lot of users...
It's just a misunderstanding...
By default in my lightening the calendar is opened.. So as a reflex I tried to create an event in this one.. what is impossible (Modification fail). Moreover in french Event and task means nearly the same.
So to resolve this problem we just have to write in the... task LOL

Shame on me lol :D  Hope this will help, I've seen some similar post

**Comment by rkokkelk** [comment]
@KTylen, Thank you for the update. If you think that a better French translation is required  please feel free to make a Pull request with the new translations.

Regarding this issue, I'll update the Github repo with the appropriate tags and releases as soon as possible and make them equivalent to the TB releases. For now I'll close this issue.
