### ISSUE TITLE
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getComplexValue]

### ISSUE THREAD

**Issue by R7914T** [rkokkelk/todo.txt-ext#37]
I have just installed Lightening. After restart i installed todo.txt. Thereafter  I keep getting the above component failure code.

Please advise what I should do to normalise the installation. I am running  Thunderbird in Gnome 16.04

**Comment by Hillside502** [comment]
Which Tbird version?

**Comment by rkokkelk** [comment]
Hi,

Possible dupicate of #35, so updating your Thunderbird will resolve this issue. Once I have some spare time I will resolve the issue for older TB versions as well. However, until that time updating TB should fix it.

Closing!
