### ISSUE TITLE
Error Message: Component returned failure code

### ISSUE THREAD

**Issue by besendorf** [rkokkelk/todo.txt-ext#39]
Hi,
I tried installing the addon and when I restarted thunderbird this following Error Message Pop Up in a Message Window.

> Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getComplexValue]

**Comment by besendorf** [comment]
Sorry. But it seems the reason is different for me. Im using TB 52.4.0 (64-bit) on Arch Linux

**Comment by besendorf** [comment]
Sorry. But it seems the reason is different for me. Im using TB 52.4.0 (64-bit) on Arch Linux

**Comment by rkokkelk** [comment]
Hi,

I'm using the exact same TB version also on Arch and unfortunately I do not have the same issue. Could you maybe elaborate on whether you maybe recently updated from an older version. 

Also could you trying entering the options again for the Add-on. For example, selecting the todo.txt and done.txt files again. This could potentially solve this issue. 

Please let me know and thank you for reporting this issue.

**Comment by besendorf** [comment]
Hi,
I reenabled the Addon today and when I restart Thunderbird the Error Message appears. Previously I used Ligthning with WebDAV and my Nextcloud installation. Maybe thats got something to do with it.
Still the same Thunderbird version.
Is there anything else I can show you to debug the error?

**Comment by rkokkelk** [comment]
Hi,

Sorry for my late reply. But this particular issue should have been fixed in your TB version. Could you therefore provide me with a copy of your done and todo.txt files and the exact file paths where there are located on your system. I can use that information for further debugging. Thank you in advance!

**Comment by tbruckmaier** [comment]
I am having the same issue with Thunderbird 52.8.0 on Ubuntu 16.04. I see the error right after installing the extension and clicking on the "switch to tasks tab", even before configuring the location of the todo.txt file.

**Comment by Lost-Projects** [comment]
HI, I have the same issue.
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getComplexValue]

TB: Version 52.9.1 (64bit), Linux Mint 18, Cinnamon 64bit 3.0.7,  4.0.4-109 generic

**Comment by Lost-Projects** [comment]
This issue appears to have resolved itself. I'm not seeing the message anymore. Possibly it was an error in the setting of the text file locations, which needs to be done in the add on preferences (tools > add ons).

**Comment by rkokkelk** [comment]
I've found the reason for this bug. This occurs if you first open the add-on and you have not specified the todo.txt or done.txt file locations. This code has now been reformatted and should show clear error messages if the todo.txt and done.txt file has not been specified. 

The new version with fixes has been uploaded to Thunderbird add-ons page and should be made available in the next few days. If there are still any issues, please feel free to reopen this issue.
