### ISSUE TITLE
Context Handling: Location Field unused?

### ISSUE THREAD

**Issue by ProfRon** [rkokkelk/todo.txt-ext#4]
This is (purely) a suggestion: Your extension has proved very useful, but I can't help but notice that contexts (i.e. tags with an at-sign, e.g. "@Work", "@Home") are not really recognized.  Yes, you can filter using them, but you cannot sort based on them. I also notice that Thunderbird (Lightning) Tasks have a field named "Location", which is currently unused (as far as I can tell (?)). I would suggest considering whether contexts can (should) be stored in the field (in much the same way that "plus-tags" are stored in "category").

**Comment by rkokkelk** [comment]
Hi,

Thank you for the suggestion. It sounds very good and I'll definitely look into it. I hope to include it in the next version.

**Comment by rkokkelk** [comment]
Contexts will be shown in the location bar in the next release. This is currently being reviewed by the Mozilla team and will be available as soon as possible.

**Comment by ProfRon** [comment]
Yes, it's there, meanwhile and yes, it does exactly what it should. 
Thank you very much!
