### ISSUE TITLE
add description field

### ISSUE THREAD

**Issue by DoctorSubtilis** [rkokkelk/todo.txt-ext#43]
Maybe after a / or \ or ^, something to add also a **description** of a task. Thank you for your beautiful and useful app/TB extension

**Comment by rkokkelk** [comment]
I thank you for your suggestion. However, I try to stick to the default functionality of the todo.txt application as much as possible. To my knowledge, this type description is not supported by the todo.txt application and therefore I would not implemented this feature.

However, if you find any relevant functionality in the todo.txt application, please feel free to notify me and I'll implemented it. Until then, I'll close this request. Still thank your request.
