### ISSUE TITLE
Bug or Feature? URLs disappear

### ISSUE THREAD

**Issue by ProfRon** [rkokkelk/todo.txt-ext#5]
URLs disapper.  When in parentheses, the parentheses disappear too.
Luckily, the original lines in the todo.txt file are not modified, but these lines (two real world examples):
> (C) @Work Learn about Elixir (programming language) https://en.wikipedia.org/wiki/Elixir_%28programming_language%29
> (C) @Work Learn about https://www.kaggle.com (https://en.wikipedia.org/wiki/Kaggle) Kaggle prediction contests

appear in Thunderbird/Lightning without the URLS, i.e. something like:
> Learn about Elixir (programming language) 
> Learn about Kaggle prediction contests

(with the normal priorities and categories).

Note: This happens if I add the to-do on the command line (todo.sh) or directly in Thunderbird/Lightning. In either case, the URLs are there in the todo.txt file, but are not there (or at least not visible) in Tb/L.

Is this intentional? 

Is there a work-around? Since todo.txt doesn't allow us to put notes on to-do's (at least without extensions), the only place to store URLs would seem to be "in line".  Or am I missing something here?

**Comment by rkokkelk** [comment]
Thanks for the feedback,

If it appear in the todo.txt then it is correctly handled by the JS library but if it is not shown by Thunderbird/Lightning then they cause the problem. I will definitely look into this issue. 

I'll try to show the URL inline, but if it appears that is not possible, is showing the URL's in the description also a viable solution? Please let me know.

**Comment by ProfRon** [comment]
Concerning your question whether the URL would be OK in the description box, if it is not possible to have it in-line:
* Showing the URL in the description is in any case better than not showing it at all.
* Showing it in the description might even be better than showing it in-line! I don't really need the URL until I'm ready to do the to-do-item.
* That said, I don't ONLY use todo.txt with the Thunderbird Extension (I also use it on the command line and on my Android devices), so questions of compatibility need to be considered: 
  * If the URL wanders into the description, will it still be in the todo.txt file for other "apps"?
  * Worse, if I enter the URL into the description (or edit it there, wherever it came from), will the material get back from the description into the in-line form for oher apps?

**Comment by rkokkelk** [comment]
This issue is fixed and the URL will be shown in the title as you would expect. This fix is available in the next version which is currently being reviewed by the Mozilla team and will be available as soon as possible.

**Comment by ProfRon** [comment]
I can confirm that. It's fixed.
Thanks!
