### ISSUE TITLE
No preferences window

### ISSUE THREAD

**Issue by racquad** [rkokkelk/todo.txt-ext#59]
![screenshot from 2019-01-25 08-45-27](https://user-images.githubusercontent.com/6040269/51734837-a0a9e380-207d-11e9-8dc5-41c210b668ab.png)

I have installed the extension on my Thunderbird (Linux Mint 19.1, Thunderbird Version: 1:60.4.0+build2-0ubuntu0.18.04.1) but it does not show the preferences button. Therefore I can't set up the path to the TXT files.

**Comment by rkokkelk** [comment]
Hi,

The settings of the add-on is configurable through the add-ons menu in the generall menu. So first open the generals menu, where you configure accounts-settings, etc.

![selection_037](https://user-images.githubusercontent.com/9407618/51868570-9c681980-234e-11e9-829d-4efe3366711b.png)

And then configure the todo-txt add-on in the add-ons menu.

![menu_035](https://user-images.githubusercontent.com/9407618/51868581-a7bb4500-234e-11e9-85c2-1cf705b18ded.png)

**Comment by racquad** [comment]
You're right!

I found it.

Thanks.
