### ISSUE TITLE
Category and Location are not being assigned from the title syntax

### ISSUE THREAD

**Issue by cjsmooth** [rkokkelk/todo.txt-ext#60]
**Example**
Say I add the following task:

(A) foobar +Dev +Home @PR

The resulting task is marked high priority, but the categories Dev and Home and the location PR are not assigned by Thunderbird and remain in the task name.

I have tried disabling "Show Projects and Contexts in the title" in the add-on preferences, but there is not way to save preferences and exiting the dialogue just resets the options.

Thunderbird version 60.6.1 on Windows 10.

**Comment by rkokkelk** [comment]
Hi,

This behaviour is expected but changing the option 'Show Projects and Contexts in title' should result in the behaviour that you want. Changing the options should immediately result in the Todo's being changed.

Testing it on TB 60.6.1 on Linux shows that it works as expected. Can you please verify that by clicking the Checkbox that it changes the Todo's. If not can you share your todo's with me so that I can test it on my system.

**Comment by CDMIUB** [comment]
I just experienced the same as cjsmooth. I tried your suggested remedy - unticking option 'Show Projects and Contexts in title'. A found that this changing this option (ticked by default) is not accepted: I am able to untick the option (however without any immediate reaction). But when i close the dialogue and re-open it, the option is still (or again) ticked. 
TB 60.6.1 (linux 64-Bit), Lightning 6.2.6.1

**Comment by CDMIUB** [comment]
If I go to the configuration editor (Edit >> Preferences, tab : Extended, button: configuration editor) and change setting extensions.todotxt.showFullTitle to false, the @ and + tags are immediately translated to Location and Category. It seem that just the dialog Extras >> AddonSettings >> Todo.txt is not accepting changes in the checkboxes.

**Comment by rkokkelk** [comment]
@CDMIUB, thanks for the feedback. Strange that this not work for you when we are using the exact same OS and versions. However, you specified that you tried to configure Todo.txt via "Extras >> AddonSettings >> Todo.txt" but I cannot find these windows / options that you specify. Can you clarify this?

I configure via Settings (the three dashes) >> Add-ons >> Todo.txt and then the changing of settings does works. Can you verify whether your are using the same windows to configure the options cause maybe the various ways of configuring the Add-on might result in these issues.

**Comment by CDMIUB** [comment]
Sorry, I forgot to mention I used German language settings, where the items are named differently. I have the menu bar enabled, then I select from the menu bar "Tools >> Add-on Preferences >> Todo.txt". Trying this on my home-PC (set to English) checking and unchecking works (!?). So could be a language-related problem? Maybe a special character breaks some character operation?  
Funny finding: If I try the same (in English version) from the hamburger symbol (aka three dashes),  and select "Add Ons >> Todo.txt", the dialog doesn't even open (!?).

**Comment by rkokkelk** [comment]
I've just tried it on my system and both windows work as expected. The only possible reason that your window fails is maybe because of some of the options that you have specified in previous Todo.txt add-on versions which are not compatible with the current option.

Because you are familiar with the ConfigEditor, could you send me the exact options that you have specified for the Todo.txt add-on via the ConfigEditor. Then I try the exact same options and see what fails. Thank you for your help, I'll try to fix it a.s.a.p.

**Comment by cjsmooth** [comment]
Hi there. Yeah my problem is also that I cannot change the preferences. I can tick or untick the checkboxes but when I close the dialogue the settings are not saved.

I use UK English language settings so I just tried rebooting by PC with US English enabled and I still experience the same bug.

Changing "extensions.todotxt.showFullTitle" to "flase" in ConfigEditor does have the desired effect. **Here are my config settings for todotxt:**
extensions.todotxt.creation;true
extensions.todotxt.done-txt;C:\Users\Me\Desktop\done.txt
extensions.todotxt.showFullTitle;true
extensions.todotxt.thunderbird;true
extensions.todotxt.todo-txt;C:\Users\Me\Desktop\todo.txt

**Here is the sample todo list I have been using:**
(B) 2019-05-17 foobar +Dev +Home @PR
2019-05-16 Interesting Article +ReadingList +Essay
2019-06-01 Task due next week due:2019-06-01

**Comment by rkokkelk** [comment]
So after I was able to reproduce the issues on Windows, I've created a fix that resolved this issue. It is strange that the 'default' method for setting preferences values worked for me but not for some other TB implementations. Setting the values specifically with JS fixed the issue. 

Version `1.0.1` contains the fix and is currently under review by Mozilla. Should be made available in the next couple of days. If the issue still persist with the new version please feel free to reopen this issue and let me know.

Thanks for the feedback!

**Comment by CDMIUB** [comment]
Great news. 
Thank you very much.


Am 30. Mai 2019 13:24:20 MESZ schrieb RoyK <notifications@github.com>:
>So after I was able to reproduce the issues on Windows, I've created a
>fix that resolved this issue. It is strange that the 'default' method
>for setting preferences values worked for me but not for some other TB
>implementations. Setting the values specifically with JS fixed the
>issue. 
>
>Version `1.0.1` contains the fix and is currently under review by
>Mozilla. Should be made available in the next couple of days. If the
>issue still persist with the new version please feel free to reopen
>this issue and let me know.
>
>Thanks for the feedback!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rkokkelk/todo.txt-ext/issues/60#issuecomment-497297797

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
