### ISSUE TITLE
Cannot select todo.txt if in hidden subdirectory

### ISSUE THREAD

**Issue by raigl** [rkokkelk/todo.txt-ext#61]
Under Linux, the command-line tool todo-txt uses the subdirectory .todo-txt/ for the files todo.txt and done.txt, but these cannot be selected as the file selection dialog does not allow to enter files or directories nor shows hidden ones.
Creating a bookmark for .todo-txt/ in the file manager allows to select the file.

**Comment by elmussol** [comment]
That would be a function of the window manager and file manager you use. In most I've used this is an optional behaviour.

pault

On 16 August 2019 20:01:45 CEST, Rainer Glaschick <notifications@github.com> wrote:
>Under Linux, the command-line tool todo-txt uses the subdirectory
>.todo-txt/ for the files todo.txt and done.txt, but these cannot be
>selected as the file selection dialog does not allow to enter files or
>directories nor shows hidden ones.
>Creating a bookmark for .todo-txt/ in the file manager allows to select
>the file.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rkokkelk** [comment]
@elmussol, is correct. This behaviour is due to your file manager and is not something that I can control within the Thunderbird extension. So therefore I'm closing this issue.
