### ISSUE TITLE
Thunderbird 68.* compatibility for Windows?

### ISSUE THREAD

**Issue by lucker999** [rkokkelk/todo.txt-ext#65]
@rkokkelk, thank you for the update a linux version (issue #63 ). Alas, many of us still stuck in Thunderbird 60, because we have no todo-txt extention for updated version in windows.

Could you please also update the windows version and upload it on the extension repo? 

Thanks in advance!

**Comment by rkokkelk** [comment]
Duplicate to #63, see comment. Closing.
