### ISSUE TITLE
Due dates dating back one day

### ISSUE THREAD

**Issue by luisfsr** [rkokkelk/todo.txt-ext#8]
Due dates are invalid, dating back one day. Perhaps because my GMT is Sao Paulo/Brazil. I can't also hide the completed tasks.

**Comment by rkokkelk** [comment]
Hi, 

Thanks for the feedback. Is it maybe possible that you provide a sample of your Done.txt file so that I can verify if it is correctly parsed. I work on with the due dates a.s.a.p. If a fix is released I'll notify you using this channel. 

Thanks again.

**Comment by luisfsr** [comment]
Of course:
[done.txt](https://github.com/rkokkelk/todo.txt-ext/files/253103/done.txt)

**Comment by luisfsr** [comment]
Of course:
[done.txt](https://github.com/rkokkelk/todo.txt-ext/files/253109/done.txt)
I edited the file and removed/altered relevant information.

**Comment by rkokkelk** [comment]
I've created a fix for the invalid due dates and the new release is current under revision at Mozilla. The new release and fix should be available within the next couple of days.

Regarding the completed task which are visible, unfortunately I cannot reproduce the errors. So could you let me know in which window the errors occurs exactly. Like in the Task window, Calendar Window or sidebar?

**Comment by rkokkelk** [comment]
Due to inactivity, I'm closing this issue.
